default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  username: restorant_api
  password: restorant_api

development:
  <<: *default
  database: restorants_dev

test:
  <<: *default
  database: restorants_test

production:
  <<: *default
  database: restorants